-- =====================================================================
-- Migration 006: Spatial Estimate (Discovery Mode) for Interface Contracts
-- =====================================================================
-- Background:
--   Interface contracts have historically been six free-text fields
--   (envelope, loadPath, ...) generated by the LLM. The dimensions in
--   those strings live only in the language model's imagination — there
--   is no validation, no clash detection, and the pre-CAD spatial_score
--   is a 1-5 vibe call.
--
--   This migration enables a "Spatial Discovery" mode where each contract
--   may carry an optional structured `spatial` block:
--     {
--       "bbox": {"x_mm": ..., "y_mm": ..., "z_mm": ..., "origin_mm": [...], "anchor": "..."},
--       "mass_g": ...,
--       "mounting_pattern": "...",
--       "reference_source": "ref_lib:bafang_m600_mid_drive" | "llm_estimate" | "rd_override",
--       "confidence": "library" | "estimate" | "rd_confirmed",
--       "rationale": "..."
--     }
--
--   Because interface_contracts is already stored as JSONB on the
--   subsystems table (see migration 003), no column changes are needed
--   for the contract itself — the spatial block is embedded as a sibling
--   key inside each contract object. This migration is therefore a no-op
--   for storage of the contract data and serves only to create the
--   OPTIONAL "spatial overlay" table used by what-if analysis.
--
-- The Discovery flow:
--   1. LLM emits contracts with embedded `spatial` blocks (Phase 2).
--   2. Python validator computes a PackageMap describing what envelope
--      and mass the design REQUIRES (descriptive, not prescriptive).
--   3. Optionally, RD can POST a hypothetical frame envelope (overlay)
--      and the validator reports clashes / overflow against it. The
--      overlay is stored per-project here so RD can iterate.
--
-- Crucially: the overlay is OPT-IN. RD never has to declare a spatial
-- budget upfront; doing so would constrain creative design. The default
-- discovery mode just shows what the design wants.
-- =====================================================================

CREATE TABLE IF NOT EXISTS project_spatial_overlay (
  project_id   uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
  overlay_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Schema convention for overlay_json:
  --   {
  --     "zones": {
  --       "downtube_battery_cavity": {"x_mm": 380, "y_mm": 80, "z_mm": 70, "anchor": "downtube_top"},
  --       ...
  --     },
  --     "mass_budget_g": {"battery_pack": 4500, "drive_unit": 4000},
  --     "notes": "hypothetical commuter frame"
  --   }
  updated_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE project_spatial_overlay IS
  'Optional what-if frame envelope for a project. Used by spatial validator to report violations against a hypothetical packaging budget. NOT required for discovery mode — leave empty to see what envelope the design requests.';

-- Helpful index for finding projects with non-empty overlays
CREATE INDEX IF NOT EXISTS idx_project_spatial_overlay_nonempty
  ON project_spatial_overlay (project_id)
  WHERE overlay_json <> '{}'::jsonb;
